site_name:        GLM.jl
repo_url:         https://github.com/JuliaStats/GLM.jl
site_description: Fit and examine generalized linear models
site_author:      JuliaStats

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
- Home: index.md
